const COUNTRY_TO_REGION = {
  France: 'europe',
  Germany: 'europe',
  Italy: 'europe',
  Spain: 'europe',
  Netherlands: 'europe',
  Belgium: 'europe',
  Switzerland: 'europe',
  Austria: 'europe',
  Portugal: 'europe',
  Ireland: 'europe',
  Poland: 'europe',
  Sweden: 'europe',
  Norway: 'europe',
  Denmark: 'europe',
  Finland: 'europe',
  Singapore: 'asia',
  Japan: 'asia',
  'South Korea': 'asia',
  Taiwan: 'asia',
  Indonesia: 'asia',
  Malaysia: 'asia',
  Thailand: 'asia',
  Vietnam: 'asia',
  Philippines: 'asia',
  'Hong Kong': 'asia',
  Brazil: 'brics-uk',
  Russia: 'brics-uk',
  India: 'brics-uk',
  China: 'brics-uk',
  'South Africa': 'brics-uk',
  'United Kingdom': 'brics-uk',
  'United States of America': 'north-america',
  Canada: 'north-america',
  Mexico: 'north-america',
};

export function regionIdForCountryName(countryName) {
  return COUNTRY_TO_REGION[countryName] || null;
}
